PaperStrike/Pjax

README.md, src/utils/DefaultTrigger.js
The [`<area>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/area) reflects a hyperlink, too.
=> Add area element support in default trigger

.github/CONTRIBUTING.md, README.md
Communicate how people should contribute.
=> Add contributing guide

babel.config.json
The [stable sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#sort_stability) isn't used so there's no need to use es.array.sort polyfill.
=> Exclude es.array.sort polyfill

package-lock.json, package.json
@babel/runtime-corejs3 (optional part of [@babel/plugin-transform-runtime](https://babel.dev/docs/en/babel-plugin-transform-runtime)) isn't used anywhere.
=> Remove @babel/runtime-corejs3

package-lock.json, package.json
In [@babel/plugin-transform-runtime][babel-plugin-transform-runtime] and [@babel/runtime][babel-runtime]'s docs, [@babel/runtime][babel-runtime] is meant to be used as a [*dependency*](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#dependencies), as this package is used in *runtime*.
However, Babel in this project is only used when bundling. Scripts in `dist/` have all the needed parts **bundled** together.
[babel-plugin-transform-runtime]: https://babel.dev/docs/en/babel-plugin-transform-runtime
[babel-runtime]: https://babel.dev/docs/en/babel-runtime
=> Use @babel/runtime as dev dependency

README.md, src/libs/executeScripts/__tests__/executeScripts.js, src/libs/executeScripts/index.js
`pjax:complete` and `pjax:success` events should fire regardless of asynchronous scripts' executive status.
=> Ignore asynchronous execution time

src/libs/executeScripts/Script.js, src/libs/executeScripts/__tests__/Script.js
* Use [`EventTarget.addEventListener`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) instead of methods of [`GlobalEventHandlers`](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers). This avoids the potential event handler overriding. (**NOTE**: No new test cases were added for this part as it is so obvious.)
* When executing an external and not-in-current-DOM script, remove it **after** its execution as it may need `document.currentScript`.
=> Use event listeners in Script lib

src/utils/DefaultTrigger.ts
=> Support target attr of links in default trigger

package.json
=> Add tsconfig to distribution

babel.config.json, src/libs/LazyHistory/index.ts, src/libs/Submission/index.ts, src/libs/executeScripts/Script.ts, src/libs/executeScripts/index.ts, src/utils/DefaultTrigger.ts
Usage of declare fields in classes was introduced in TS 3.7, documented [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier).
=> Use declare fields to reduce bundle size

.eslintrc.json, package-lock.json, package.json, src/utils/DefaultTrigger.ts, tsconfig.json
Changes in @types/web 0.0.17 - Changes here:
* Usage of `SubmitEvent` interface in 'submit' events
- Remove `SubmitEvent` notices
* `DOMException` extends `Error`
- Re-enable `@typescript-eslint/no-throw-literal` ESLint rule
[@types/web - npm](https://www.npmjs.com/package/@types/web)
=> Use @types/web@^0.0.17

README.md, README.zh-Hans.md
=> Add Simplified Chinese README

README.md, README.zh-Hans.md, src/__mocks__/index.ts, src/__tests__/switchDOM.ts, src/index.ts, src/switchDOM.ts
=> Fix broken cacheMode option and rename to cache

babel.config.json
See [Compiler assumptions · Babel](https://babel.dev/docs/en/assumptions).
=> Use Babel assumptions to reduce bundle size

package-lock.json, package.json
It's only used to parse config file. And it's 2.0.3 (https://github.com/PaperStrike/Pjax/commit/08f7726ba066837ba41651a97e39e57c32371795) 's blocker, as it requires tslib.
=> Replace @rollup/plugin-typescript

babel.config.json, package-lock.json, package.json, rollup.config.ts
- Use [@rollup/plugin-babel's helpers](https://github.com/rollup/plugins/blob/53fb18c0c2852598200c547a0b1d745d15b5b487/packages/babel/README.md#helpers).
=> Replace babel helpers dependencies

README.md, README.zh-Hans.md, src/preparePage.ts, src/weakLoad.ts, test/preparePage.test.ts
- Implement #102 by switching the DOM for targets that doesn't have a `#`, even if it's in the same path.
- Conform with the [scroll to the fragment | HTML Standard](https://html.spec.whatwg.org/multipage/browsing-the-web.html#scroll-to-the-fragment-identifier) when preparing the page.
=> Conform with standard fragment navigation

package-lock.json, package.json, test/index.ts, test/switchDOM.test.ts
- Remove unneeded `@sliphua/expect` by intro `module: false` and `graceful-fs: false` into package `browser` field
- Adapt to `onfetch` ^0.7.0
- Adapt to `@sinonjs/fake-timers` ^8.0.1
=> Manually update dependencies that breaks

src/libs/executeScripts/Script.ts
Reduces bundle size. Matches [JavaScript MIME type | MIME Sniffing Standard](https://mimesniff.spec.whatwg.org/#javascript-mime-type).
```js
/^((application|text)\/(x-)?(ecma|java)script|text\/(javascript1\.[0-5]|(j|live)script))$/
```
Regex visualized by [https://jex.im/regulex](https://jex.im/regulex).
=> Use regex to match script types

package-lock.json, package.json
- Require `playwright-test@^7.2.0`, which works well with source-mapped dependencies.
- Require `onfetch@^0.7.3`, which distributes its source maps.
=> Use source-mapped onfetch
